spring:
  cloud:
    gateway:
      routes:
        - id: shop-route
          predicates:
            - Path=/api/shop/**
          uri: lb://SHOP-SERVICE
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
